### PR TITLE
Safer version check

### PR DESCRIPTION
**Pull request by mvandegarde**
This prevents facter from getting stuck in an interactive session.

### CODE REVIEW

**Review by smortex — CHANGES_REQUESTED** [review]
Thanks!  Please update the test suite accordingly :wink:

**Comment by mvandegarde** [comment]
> Thanks! Please update the test suite accordingly 😉

Should be ok now. Unfortunately I can't verify if this works the same on the windows binary, or on the regular splunk_binary. I'd be happy to do the same there but i can't even find the parameters i'm adding right now in the splunk forwarder documentation, i've only tested & confirmed that they do work.

**Review by smortex — COMMENTED** [review]
Ah…  we do not have CI for windows so who knows :shrug:.  Maybe windows users will send a PR to fix windows support if it broke and we will issue a new patch release then so probably not a big issue.

Can you please combine your commits in a single one?

From your working directory:

```
git rebase -i origin/master # Interactively rewrite history
```

This will bring your editor.  Keep the first line unchanged, and replace `pick` with `squash` for all subsequent lines.  Save and quit, your editor will allow you to combine the commit messages in a single commit message.

Then push your updated branch:

```
git push -f            # Send the changes (-f is required because we re-wrote history)
```

Thanks!

**Review by smortex — APPROVED** [review]

**Comment by root-expert** [comment]
This PR superseded 

* #287 
* #253

**Pull request merged**
