### PR TITLE
Add new types

### PR DESCRIPTION
**Pull request by treydock**
Add Splunk_deploymentclient and Splunkforwarder_deploymentclient type
Add splunk_alert_actions type
Add purge_deploymentclient parameter to splunk and splunk::forwarder
Add purge_alert_actions to splunk class

### CODE REVIEW

**Comment by dhoppe** [comment]
@treydock Could you please take care of the Rubocop issue?

**Comment by myguelra** [comment]
Splunkforwarder_deploymentclient type will be very helpful for me,  I hope you can add this type soon.
Keep the good work.

**Comment by treydock** [comment]
@dhoppe rubocop fixes are in place but now unit tests fail due to changes in puppet-lint.

**Comment by dhoppe** [comment]
@treydock You can fix this by running puppet-lint -f manifests/*.

**Comment by treydock** [comment]
I created #101 for lint fixes

**Comment by bastelfreak** [comment]
Hey @treydock, thanks for the PR and sorry for the late response :(
Can you please rebase? Than I'm happy to merge it.

**Comment by treydock** [comment]
@bastelfreak Rebased.

**Pull request closed without merging**
