### PR TITLE
fix unknown variable: staged_package

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
This is a proposed fix for https://github.com/voxpupuli/puppet-splunk/issues/169. This reveals new errors that I don't quite understand yet. I'm not sure if we've multiple bugs in the code or if this patch is wrong. @TraGicCode and idea?

**Comment by TraGicCode** [comment]
Yea i believe that was what was proposed.  It's more of a patch then a true fix of the actual problem.

**Comment by TraGicCode** [comment]
This seems fine to me.  I think the these errors were hidden by this bug you just fixed.  Can i merge this?

**Comment by TraGicCode** [comment]
Based on the changes #180 was trying to make i understand now why it's failing.  I reported this a while back #151.

**Pull request merged**
