### PR TITLE
Release v6.1.0

### PR DESCRIPTION
**Pull request by TraGicCode**
Can somone review the changelog and see if i need to update any titles/labels.

There exist only features and bugs fixes in this release so i did a minor bump

### CODE REVIEW

**Comment by bastelfreak** [comment]
@TraGicCode looks good to me. Do you know if any of the changes are a breaking change?

**Comment by TraGicCode** [comment]
From what i checked i didn't see a breaking change.  No new parameters and none removed

**Comment by bastelfreak** [comment]
do you want to run the release_travis rake task?

**Comment by TraGicCode** [comment]
I'm on it!

**Pull request merged**
