### PR TITLE
v6.3.0 release

### PR DESCRIPTION
**Pull request by TraGicCode**
No Breaking changes and just features :)

### CODE REVIEW

**Comment by bastelfreak** [comment]
@TraGicCode could you please check the used email address in this commit? It isn't associated with your github account.

**Comment by TraGicCode** [comment]
@bastelfreak I did this for a reason.  I'm using github's built in feature to hide private email addresses.

https://github.com/blog/2346-private-emails-now-more-private

Does this break anything?

**Comment by TraGicCode** [comment]
Okay i see what happened.  I made this change to my local github profile AFTER i made this commit.  1 second and i'll rewrite the commit history for this  PR.

**Comment by TraGicCode** [comment]
@bastelfreak Fixed the email.  Sorry about that.

**Comment by bastelfreak** [comment]
that is totally fine. I think I'm the only one checking for that :D. It is not imporant, it just makes the history a bit cleaner.

**Comment by bastelfreak** [comment]
merged and did the rake task

**Pull request merged**
